# Generated by Django 4.0 on 2022-03-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Bullet', max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=70, null=True)),
                ('about', models.TextField(blank=True, max_length=355, null=True)),
                ('shortAbout', models.CharField(blank=True, max_length=70, null=True)),
                ('topSpeed', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('bike1', models.ImageField(null=True, upload_to='')),
                ('bike2', models.ImageField(null=True, upload_to='')),
                ('bike3', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
