# Generated by Django 4.0 on 2022-03-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlePrev', models.CharField(max_length=20, null=True)),
                ('content', models.TextField(blank=True, max_length=375, null=True)),
                ('question', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
